linters:
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - unconvert
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/GainForest/hypercerts-cli

issues:
  exclude-use-default: false
