version: 2

builds:
  - main: ./cmd/hc
    binary: hc
    ldflags:
      - -s -w -X github.com/GainForest/hypercerts-cli/cmd.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
