version: 2

builds:
  - main: .
    binary: hyper
    ldflags:
      - -s -w -X github.com/hypercerts-org/hyper/cmd.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
